---
- include_vars: dotfiles.yml
- name: Ensure dotfiles repository is cloned locally.
  git:
    repo: "{{dotfile_repo}}"
    dest: "/{{username}}/.dot_files"
- name: Ensure dotfiles repository is cloned locally.
  file:
    path: "/{{username}}/.{{item}}"
    src: "/{{username}}/.dot_files/{{item}}"
    state: link
  with_items: dotfiles_to_link

