---
dotfile_repo: https://github.com/wusher/dot_files.git
dotfiles_to_link: 
  - gemrc
  - gitconfig
  - tmux.conf
  - vimrc 
  - zshrc
misc_config_files:
  - dest: Library/Preferences/com.googlecode.iterm2.plist
    src: iterm2.plist
