---
downloads: ~/.ansible-downloads/
homebrew_installed_packages:
  - ack
  - ansible
  - boot2docker
  - docker
  - fig
  - git
  - go
  - hr
  - jq
  - macvim
  - nvm
  - postgresql
  - rbenv
  - reattach-to-user-namespace
  - ruby-build
  - sqlite
  - tmux
  - tree
  - watch
  - zsh

homebrew_taps:
  - caskroom/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - alfred
  - amethyst
  - caffeine
  - dash
  - disk-inventory-x
  - dropbox
  - evernote
  - firefox
  - fluid
  - flux
  - github
  - google-chrome
  - iterm2
  - kindle
  - macpaw-gemini
  - macvim
  - nvalt
  - rdio
  - sequel-pro
  - skitch
  - skype
  - slack
  - virtualbox
  - vlc
  - ynab
